//
//  RepositoryListWorker.swift
//  github-bests
//
//  Created by Paulo Lourenço on 02/08/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit

class RepositoryListWorker {

    var dataSource: SearchAPIDataSource
    
    init(dataSource: SearchAPIDataSource = SearchAPI()) {
        self.dataSource = dataSource
    }
    
    func getRepositories(request: RepositoryList.Request) -> Promise<SearchResults<[Repository]>> {
        return dataSource.searchRepositories(query: request.query, sort: request.sort, page: request.page, itemsPerPage: request.itemsPerPage)
    }
    
}
