//
//  RepositoryListModels.swift
//  github-bests
//
//  Created by Paulo Lourenço on 02/08/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RepositoryList {
    
    // MARK: Use cases
    
    struct Request {
        var query: String
        var sort: String
        var page: Int
        var itemsPerPage: Int
    }
    
    struct ViewModel {
        var list: [Repository]
    }
}
