//
//  RepositoryListPresenter.swift
//  github-bests
//
//  Created by Paulo Lourenço on 02/08/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RepositoryListPresentationLogic {
    func presentList()
    func presentError(error: Error)
    func presentLoading(screen: Bool)
    func stopLoading(screen: Bool)
}

class RepositoryListPresenter: RepositoryListPresentationLogic {
    weak var viewController: RepositoryListDisplayLogic?
    
    func presentList() {
        viewController?.displayList()
    }
    
    func presentError(error: Error) {
        viewController?.showError(title: nil, message: error.localizedDescription)
    }
    
    func presentLoading(screen: Bool) {
        if screen {
            viewController?.showScreenLoading()
        } else {
            viewController?.showPaginationLoading()
        }
    }
    
    func stopLoading(screen: Bool) {
        if screen {
            viewController?.hideScreenLoading()
        } else {
            viewController?.hidePaginationLoading()
        }
    }
}
