# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Gera relatório de code covarage do projeto"
  lane :custom_lane do

        slather(
            proj: "github-bests.xcodeproj",
            workspace: "github-bests.xcworkspace",
            scheme: "github-bests",
            html: true,
            show: true,
            output_directory: "fastlane/html",
            verbose: true
        )

  end
end
